# config/skills_config.yaml

slowmo:
  duration_ms: 3000
  cooldown_ms: 1000
  paddle_color: [0, 150, 255]
  fog_duration_ms: 2000 # From SKILL_CONFIGS.py
  trail_color: [0, 200, 255]
  # bar_color: [0, 200, 255] # UI related, from SKILL_CONFIGS.py
  clock_color: [255, 255, 255, 100]
  clock_radius: 50 # From SKILL_CONFIGS.py (used as clock_radius_logic_px in skill)
  clock_line_width: 4 # From SKILL_CONFIGS.py (used as clock_line_width_logic_px in skill)
  # --- Parameters from SlowMoSkill that were in its internal default cfg if not in SKILL_CONFIGS ---
  # These should now be taken from above if they map, or skill uses internal defaults if still not present.
  slow_time_scale: 0.15 # Not in SKILL_CONFIGS.py under 'slowmo', skill will use its own default if not found by key
  fadeout_duration_ms: 500 # Not in SKILL_CONFIGS.py under 'slowmo'
  shockwave_expand_speed_logic_px: 30 # Not in SKILL_CONFIGS.py under 'slowmo'
  owner_paddle_speed_multiplier: 10

long_paddle:
  duration_ms: 3000
  cooldown_ms: 5000
  paddle_color: [0, 255, 100]
  paddle_multiplier: 2.0 # SKILL_CONFIGS.py has 2 (int)
  animation_ms: 300
  # bar_color: [0, 100, 0] # UI related

soul_eater_bug:
  duration_ms: 8000
  cooldown_ms: 1000 # 建議將冷卻時間調整回一個更合理的值，例如 10000 或 12000
  bar_color: [150, 50, 200]
  bug_image_path: "assets/soul_eater_bug.png"
  bug_display_scale_factor: 2.0

  sound_activate: "assets/bug_activate.mp3"
  sound_crawl: "assets/bug_crawl.mp3"
  sound_hit_paddle: "assets/bug_hit_paddle.mp3"
  sound_score: "assets/bug_score.mp3"

  # --- 新增 RL 相關參數 ---
  rl_model_path: "bug_models/bug_agent_ep3200.pth" # ⭐️ 您的噬魂蟲 RL 模型路徑
  # bug_rl_action_type: "discrete_xy_thrust" # ⭐️ (可選) 動作類型說明
  bug_x_rl_move_speed: 0.01  # ⭐️ (可選) 如果動作是離散推力，X方向每單位動作的速度
  bug_y_rl_move_speed: 0.01  # ⭐️ (可選) 如果動作是離散推力，Y方向每單位動作的速度

  # --- 保留或調整的參數 ---
  base_y_speed: 0.0 # ⭐️ 基礎的 Y 軸趨向速度 (可以讓 RL 在此基礎上調整)
                       #    或者如果 RL 完全控制 Y 軸，則可設為 0 或移除

  # --- 移除或註解掉的舊硬編碼移動參數 ---
  target_update_interval_frames: 10 # ⭐️ RL 模型可能不需要這個，可以考慮移除